### ISSUE TITLE
Pumi : un fichier est inaccessible dans son format natif (.wav)

### ISSUE THREAD

**Issue by maxime-fily** [CNRS-LACITO/Pangloss_deposits-and-metadata#10]
le fichier à l'URL https://cocoon.huma-num.fr/data/daudey/masters/WD2011KZ04.wav n'est pas accessible à l'utilisateur non admin, alors que le mp3 est lui parfaitement accessible. Est-il possible de changer cela et de rendre accessible le wav ?
doi de la resource : https://doi.org/10.24397/pangloss-0007427

**Comment by alexis-michaud** [comment]
Ah oui! Le fichier original au format wav est proposé au téléchargement (et la licence affichée l'autorise)...
![image](https://github.com/CNRS-LACITO/Pangloss_deposits-and-metadata/assets/6072524/347bdd9e-49d7-40d1-b192-238ea3670994)
... mais quand on clique, le site lien indique que l'accès est interdit.

**Comment by sguillaume** [comment]
C'est réglé !
