### ISSUE TITLE
Erreur du déposant pour deux métadonnées de deux dépôts

### ISSUE THREAD

**Issue by maxime-fily** [CNRS-LACITO/Pangloss_deposits-and-metadata#12]
Les dates sont erronnées sur deux de mes dépôts : 
https://doi.org/10.24397/pangloss-0007858 : la bonne date est 2019-10-01
https://doi.org/10.24397/pangloss-0007861 : la bonne date est 2019-10-04

**Comment by alexis-michaud** [comment]
Ca c'est quelque chose qui doit pouvoir se modifier grâce à l'interface utilisateur de Cocoon
On s'identifie avec son compte déposant, puis on a accès à une interface simple pour modifier les métadonnées
Démo sur demande !

**Comment by maxime-fily** [comment]
Vu ! Merci !
